
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
  namespace: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: apache2-storage
          subPath: html
      volumes:
      - name: apache2-storage
        persistentVolumeClaim:
          claimName: apache2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: apache2-service
  namespace: apache
spec:
  selector:
    app: apache2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30090
  type: NodePort


